### DISCUSSION TITLE
There is no workflow for spell chek

### DISCUSSION THREAD

**Discussion by realamirhe** [chintan9/plyr-react#673] [Q&A] [answered]
There is no `.github/workflows/spellcheck.yml` related `.typo-ci.yml` file is that intentional? Could we use it I'm existed to see the result 😍 

Here is a simple installation grabbed from main [doc](https://github.com/TypoCI/spellcheck-action#installation)

```yml
# Add to: .github/workflows/spellcheck.yml
name: Typo CI

on:
  push:
    branches-ignore:
      - master
jobs:
  spellcheck:
    name: Typo CI (GitHub Action)
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: TypoCheck
      uses: typoci/spellcheck-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ```
